<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	function formatDateTime(value: string) {
		return new Date(value).toLocaleString('en-US', {
			month: 'short',
			day: 'numeric',
			year: 'numeric',
			hour: 'numeric',
			minute: '2-digit'
		});
	}

	function relativeTime(value: string) {
		const now = new Date().getTime();
		const then = new Date(value).getTime();
		const diffMs = now - then;

		const minutes = Math.floor(diffMs / 60000);
		const hours = Math.floor(diffMs / 3600000);
		const days = Math.floor(diffMs / 86400000);

		if (minutes < 1) return 'Just now';
		if (minutes < 60) return `${minutes} min ago`;
		if (hours < 24) return `${hours} hr ago`;
		return `${days} day${days === 1 ? '' : 's'} ago`;
	}
</script>

<svelte:head>
	<title>Notifications | DollarView</title>
</svelte:head>

<div class="space-y-8">
	<section
		class="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-white/90 p-6 shadow-[0_20px_60px_rgba(15,23,42,0.08)] md:p-8 xl:p-10 dark:border-slate-800 dark:bg-slate-900/90"
	>
		<div class="pointer-events-none absolute inset-0">
			<div
				class="absolute -left-24 top-0 h-64 w-64 rounded-full bg-blue-500/10 blur-3xl dark:bg-blue-500/20"
			></div>
			<div
				class="absolute -right-20 bottom-0 h-72 w-72 rounded-full bg-slate-300/30 blur-3xl dark:bg-slate-700/30"
			></div>
		</div>

		<div class="relative flex flex-wrap items-end justify-between gap-6">
			<div class="max-w-2xl">
				<p
					class="mb-4 text-xs font-semibold uppercase tracking-[0.35em] text-blue-600 dark:text-blue-400"
				>
					Notification center
				</p>

				<h1
					class="text-4xl font-extrabold leading-tight tracking-tight text-slate-900 md:text-5xl dark:text-white"
				>
					View triggered alerts in one place.
				</h1>

				<p class="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-300">
					See the latest reminders, warning triggers, and scheduled alert activity generated by
					DollarView.
				</p>
			</div>

			<div
				class="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600 shadow-sm dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300"
			>
				{data.notifications.length} notification{data.notifications.length === 1 ? '' : 's'}
			</div>
		</div>
	</section>

	{#if data.error}
		<div
			class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-900/50 dark:bg-rose-950/40 dark:text-rose-300"
		>
			{data.error}
		</div>
	{/if}

	{#if !data.business}
		<div
			class="rounded-[2rem] border border-dashed border-slate-300 bg-white/70 px-6 py-12 text-center shadow-sm dark:border-slate-700 dark:bg-slate-900/60"
		>
			<h2 class="text-xl font-semibold text-slate-900 dark:text-white">No workspace found</h2>
			<p class="mt-3 text-slate-600 dark:text-slate-400">
				Notifications will appear here once your business workspace is set up.
			</p>
		</div>
	{:else if data.notifications.length === 0}
		<div
			class="rounded-[2rem] border border-dashed border-slate-300 bg-white/70 px-6 py-12 text-center shadow-sm dark:border-slate-700 dark:bg-slate-900/60"
		>
			<h2 class="text-xl font-semibold text-slate-900 dark:text-white">No notifications yet</h2>
			<p class="mt-3 text-slate-600 dark:text-slate-400">
				Triggered alerts will appear here after your scheduled alert runner processes them.
			</p>
		</div>
	{:else}
		<div class="grid gap-5">
			{#each data.notifications as notification}
				<div
					class="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-[0_20px_40px_rgba(15,23,42,0.08)] dark:border-slate-800 dark:bg-slate-900"
				>
					<div class="flex flex-wrap items-start justify-between gap-4">
						<div class="min-w-0">
							<div class="flex flex-wrap items-center gap-2">
								<h2 class="truncate text-lg font-bold text-slate-900 dark:text-white">
									{notification.title}
								</h2>

								<span
									class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-600 dark:bg-blue-500/10 dark:text-blue-300"
								>
									Alert
								</span>
							</div>

							<p class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">
								{notification.message}
							</p>
						</div>

						<div class="text-right">
							<p class="text-sm font-medium text-slate-900 dark:text-white">
								{relativeTime(notification.created_at)}
							</p>
							<p class="mt-1 text-xs text-slate-500 dark:text-slate-400">
								{formatDateTime(notification.created_at)}
							</p>
						</div>
					</div>

					<div class="mt-5 grid gap-3 sm:grid-cols-3">
						<div class="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950">
							<p
								class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400"
							>
								Sent at
							</p>
							<p class="mt-2 text-sm font-medium text-slate-900 dark:text-white">
								{formatDateTime(notification.sent_at)}
							</p>
						</div>

						<div class="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950">
							<p
								class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400"
							>
								Created
							</p>
							<p class="mt-2 text-sm font-medium text-slate-900 dark:text-white">
								{formatDateTime(notification.created_at)}
							</p>
						</div>

						<div class="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950">
							<p
								class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400"
							>
								Alert ID
							</p>
							<p class="mt-2 break-all text-sm font-medium text-slate-900 dark:text-white">
								{notification.alert_id}
							</p>
						</div>
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>